# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.14
FROM python:${PYTHON_VERSION}-slim-bookworm AS base
FROM base AS builder

ENV PIP_PARAMS=""
ENV PIP_VERSION=26.1.2
ENV EXTRA_PACKAGES="relstorage==4.3.0 psycopg2==2.9.12 python-ldap==3.4.7"

RUN mkdir /wheelhouse

RUN <<EOT
    set -e
    apt-get update
    buildDeps="build-essential curl libbz2-dev libffi-dev libjpeg62-turbo-dev libsasl2-dev libldap2-dev libopenjp2-7-dev libpcre3-dev libpq-dev libssl-dev libtiff6 libtiff5-dev libxml2-dev libxslt1-dev wget unzip zlib1g-dev"
    apt-get install -y --no-install-recommends $buildDeps
    pip install -U "pip==${PIP_VERSION}"
    pip install -U "zc.buildout==5.2.0.0" "wheel==0.47.0" "setuptools==81.0.0"
    rm -rf /var/lib/apt/lists/* /usr/share/doc
    curl -L -o workspace.zip https://github.com/plone/buildout.coredev/archive/refs/heads/6.2.zip
    unzip workspace.zip
    mv buildout.coredev-6.2 /workspace
EOT

WORKDIR /workspace
COPY --chown=500:500 /helpers/pip-from-buildout-coredev.py ./

# Generate pip-requirements.txt
RUN <<EOT
    set -e
    python pip-from-buildout-coredev.py
    pip wheel -r pip-requirements.txt -c pip-constraints.txt --wheel-dir=/wheelhouse
    pip wheel $EXTRA_PACKAGES -c pip-constraints.txt --wheel-dir=/wheelhouse
EOT

FROM base

ENV PIP_PARAMS=""
ENV PIP_VERSION=26.1.2

LABEL maintainer="Plone Community <dev@plone.org>" \
      org.label-schema.name="plone-backend" \
      org.label-schema.description="Plone 6.2 nightly backend image using Python 3.14" \
      org.label-schema.vendor="Plone Foundation"

COPY --from=builder /wheelhouse /wheelhouse

RUN <<EOT
    set -e
    useradd --system -m -d /app -U -u 500 plone
    runDeps="git libjpeg62 libopenjp2-7 libpq5 libtiff6 libxml2 libxslt1.1 lynx netcat-openbsd poppler-utils rsync wv busybox libmagic1 gosu make"
    apt-get update
    apt-get install -y --no-install-recommends $runDeps
    busybox --install -s
    rm -rf /var/lib/apt/lists/* /usr/share/doc
    mkdir -p /data/filestorage /data/blobstorage /data/log /data/cache
EOT

WORKDIR /app

RUN <<EOT
    set -e
    python -m venv .
    ./bin/pip install -U "pip==${PIP_VERSION}"
    ./bin/pip install --force-reinstall --no-index --no-deps ${PIP_PARAMS} /wheelhouse/*
    find . \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' +
    rm -rf .cache
EOT

COPY skeleton/ /app

RUN <<EOT
    set -e
    ln -s /data var
    find /data  -not -user plone -exec chown plone:plone {} \+
    find /app -not -user plone -exec chown plone:plone {} \+
EOT

EXPOSE 8080
VOLUME /data

HEALTHCHECK --interval=10s --timeout=5s --start-period=30s CMD wget -q http://127.0.0.1:8080/ok -O - | grep OK || exit 1

ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
CMD ["start"]
