# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.11
ARG PLONE_VERSION
FROM plone/server-builder:${PLONE_VERSION}

LABEL maintainer="Plone Community <dev@plone.org>" \
      org.label-schema.name="server-dev" \
      org.label-schema.description="Plone development image using Python $PYTHON_VERSION" \
      org.label-schema.vendor="Plone Foundation"

WORKDIR /app
# COPY --from=builder --chown=500:500 /app /app

ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
CMD ["start"]
