# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.12
ARG PLONE_VERSION
FROM plone/server-builder:${PLONE_VERSION} AS builder

ARG PLONE_VERSION

# Remove Volto support from builder image, this is Classic UI
RUN /app/bin/pip uninstall -y plone.volto

FROM plone/server-prod-config:${PLONE_VERSION}

ARG PYTHON_VERSION
ARG PLONE_VERSION

LABEL maintainer="Plone Community <dev@plone.org>" \
      org.label-schema.name="plone-classicui" \
      org.label-schema.description="Plone $PLONE_VERSION Classic UI image using Python $PYTHON_VERSION" \
      org.label-schema.vendor="Plone Foundation"

# Use /app as the workdir
WORKDIR /app

# Copy /app from builder
COPY --from=builder --chown=500:500 /app /app

# Link /data (the exposed volume) into /app/var
RUN ln -s /data /app/var

# Setup default type for site creation to be classic
ENV TYPE=classic
