%define INSTANCE /app
instancehome $INSTANCE

%define CLIENTHOME $(CLIENT_HOME)
clienthome $CLIENTHOME

debug-mode $(DEBUG_MODE)
security-policy-implementation $(SECURITY_POLICY_IMPLEMENTATION)
verbose-security $(VERBOSE_SECURITY)
default-zpublisher-encoding $(DEFAULT_ZPUBLISHER_ENCODING)

<environment>
    CHAMELEON_CACHE $INSTANCE/var/cache
</environment>

<dos_protection>
  form-memory-limit $(ZOPE_FORM_MEMORY_LIMIT)
  form-disk-limit $(ZOPE_FORM_DISK_LIMIT)
  form-memfile-limit $(ZOPE_FORM_MEMFILE_LIMIT)
</dos_protection>

<zodb_db main>
    # Blob-enabled FileStorage database
    %import zodb_pgjsonb
    <pgjsonb>
        dsn $(ZODB_PGJSONB_DSN)
        history-preserving $(ZODB_PGJSONB_HISTORY_PRESERVING)

        s3-endpoint-url $(ZODB_PGJSONB_S3BLOBS_ENDPOINT_URL)
        s3-use-ssl $(ZODB_PGJSONB_S3BLOBS_USE_SSL)
        s3-bucket-name $(ZODB_PGJSONB_S3BLOBS_BUCKET_NAME)
        s3-access-key $(ZODB_PGJSONB_S3BLOBS_ACCESS_KEY)
        s3-secret-key $(ZODB_PGJSONB_S3BLOBS_SECRET_KEY)
        s3-region $(ZODB_PGJSONB_S3BLOBS_REGION)
        s3-prefix $(ZODB_PGJSONB_S3BLOBS_PREFIX)

        blob-threshold $(ZODB_PGJSONB_S3BLOBS_THRESHOLD)
        blob-cache-dir $(ZODB_PGJSONB_S3BLOBS_CACHE_DIR)
        blob-cache-size $(ZODB_PGJSONB_S3BLOBS_CACHE_SIZE)

    </pgjsonb>

    mount-point /
    cache-size $(ZODB_CACHE_SIZE)
</zodb_db>
