name: Release Image to Container registry

on:
  workflow_call:
    inputs:
      plone-version:
        required: true
        type: string
      image-name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      platforms:
        required: true
        type: string
      load:
        required: false
        type: boolean
        default: false
      push:
        required: false
        type: boolean
        default: false
      is-latest:
        required: false
        type: boolean
        default: false
    secrets:
      ghcr-registry-username:
        required: true
      ghcr-registry-password:
        required: true
      docker-registry-username:
        required: true
      docker-registry-password:
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.image-name }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}.{{patch}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ inputs.is-latest }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.ghcr-registry-username }}
          password: ${{ secrets.ghcr-registry-password }}

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker-registry-username }}
          password: ${{ secrets.docker-registry-password }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ inputs.platforms }}
          context: .
          file: ${{ inputs.dockerfile }}
          build-args: |
            PLONE_VERSION=${{ inputs.plone-version }}
          push: ${{ inputs.push && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: ${{ inputs.load }}
